# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    PJ\UserBundle\Entity\User: sha512
    

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          moderator:   {password: moderatorpass, roles: [ 'ROLE_MODERATOR' ]}
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    main:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: /platform
      logout:
        path:       logout
        target:     /platform
      remember_me:
        secret:     %secret%
      
  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https 
