<?php

namespace PJ\BlogBundle\Repository;

/**
 * ConsoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsoleRepository extends \Doctrine\ORM\EntityRepository
{
}
