<?php

namespace PJ\BlogBundle\Repository;

/**
 * GalleryImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
